language: python
python:
  - "3.8.6"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python -m pytest tests
env:
  global:
    - secure: "mKVb817XQpUZodGRAeIY2owChWxFI9Hw3SetihLY1lCcfioaYm9N4sfR6jxUnGKQ6o7u0o2H+Om2ujkUWtZl3vWFAHCodII/GUd2+ZnZI3SbWeKZopN7/6vWXIfpW3lDI5+9dTb8T1v2upU9FBlfNshfd49RZ9drqqp6m5eZsztliObEwQsDTr3rTMHMb8O6iJJ35Xusg6QLcTE78T9FYeiajb3dt45PuuhbdiXnp09L+Xr1l4z+vAkUjekXLFB6eXX3mDwR3pG09IHzfyc87Wx1LrMgB9BQCloWga4DD+vVhvEz8LHO4XVIfk7OFOWqlEPvO0lJizrfJw/VsKZtlDqJwMhwfLs3F0zd5osslPh7GJNMj5uSSqF8VOelrirZbNcF9FtZfcj5Lf5rz5+uSM4pDsCym5WZ4yM3s8YATl7Jcpb+URaje6YHmH49a8/hmctDoV9cQxYCymwROKhaeythrLzepWRJyBtLPHqGbLpGXpmcRUvZzXA8lvM/Eabe98nxWESdd1Kvox/p7x6cxpWVzZa5iHJxLtHeoftYqY4pzlSFk9YV0/FD+df328seifsatVy/63A26W4aKJZjISdP4MGnB8mkgm7xuDyPBEl3RWiCcPsIU39bgDkonr3yCKM9l1CPKYbFGHo98Q044hb9J/d/aCOq3gM91ET1qJo="
